# -*- coding: utf-8 -*-
"""sfd_&_bmd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rl9R7f8S2gYpimcDGrJ-PL3f3AprFOXZ
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf
import sklearn
import torch

data = pd.read_csv('/content/SFS_Screening_SFDBMD.xlsx - Sheet1.csv')
print(data.head())

print(data.info())

print(data.describe())

print(data.isnull().sum())

numerical_features = data.select_dtypes(include=np.number).columns
for col in numerical_features:
  plt.figure()
  sns.histplot(data[col], kde=True)
  plt.title(f'Distribution of {col}')
  plt.show()

correlation_matrix = data.corr()
plt.figure(figsize=(10, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Matrix')
plt.show()

distance = data["Distance (m)"]
shear_force = data["SF (kN)"]
bending_moment = data["BM (kN-m)"]

fig, ax = plt.subplots(2, 1, figsize=(10, 8))

# Plot SFD with shaded area below the curve
ax[0].plot(distance, shear_force, marker="o", linestyle="-", color="b", label="Shear Force (kN)")
ax[0].fill_between(distance, shear_force, where=(shear_force > 0), interpolate=True, color='skyblue', alpha=0.5) # Shade positive values
ax[0].fill_between(distance, shear_force, where=(shear_force < 0), interpolate=True, color='skyblue', alpha=0.5) # Shade negative values
ax[0].axhline(0, color="black", linewidth=1)
ax[0].set_title("Shear Force Diagram (SFD)")
ax[0].set_xlabel("Distance (m)")
ax[0].set_ylabel("Shear Force (kN)")
ax[0].legend()
ax[0].grid(True)

# Plot BMD with shaded area below the curve
ax[1].plot(distance, bending_moment, marker="o", linestyle="-", color="r", label="Bending Moment (kN-m)")
ax[1].fill_between(distance, bending_moment, where=(bending_moment > 0), interpolate=True, color='lightcoral', alpha=0.5) # Shade positive values
ax[1].fill_between(distance, bending_moment, where=(bending_moment < 0), interpolate=True, color='lightcoral', alpha=0.5) # Shade negative values
ax[1].axhline(0, color="black", linewidth=1)
ax[1].set_title("Bending Moment Diagram (BMD)")
ax[1].set_xlabel("Distance (m)")
ax[1].set_ylabel("Bending Moment (kN-m)")
ax[1].legend()
ax[1].grid(True)


plt.tight_layout()
plt.show()